name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements-test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        env:
          OPENSEARCH_HOST: http://localhost:9200
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: testdb
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          GEMINI_API_KEY: fake-key-for-tests
        run: |
          pytest -v --maxfail=1 --disable-warnings tests/

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.8.4

      - name: Run Ruff
        run: |
          ruff check --output-format=github . || true
